{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.billyrosty",
    "module": "cyberfactions-api",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cyberfactions-api-0.2.0.jar",
          "url": "cyberfactions-api-0.2.0.jar",
          "size": 41823,
          "sha512": "56e665983d92ec7a776b35707a532990912b849b4527ce7b8074cca553dcded0f6e80e0b7d712c699ba302c2d52c487316e68df6b98291716f0c62f68199070a",
          "sha256": "2637312a057332f621428d1eef40b7b81c54b9b3b2c53790bffff94e34cf68a0",
          "sha1": "73cf4370df1e54bcddd35c9e8b68e808cc787338",
          "md5": "da3f2f4cda85e4774cb7fb624503ac09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-0.2.0.jar",
          "url": "cyberfactions-api-0.2.0.jar",
          "size": 41823,
          "sha512": "56e665983d92ec7a776b35707a532990912b849b4527ce7b8074cca553dcded0f6e80e0b7d712c699ba302c2d52c487316e68df6b98291716f0c62f68199070a",
          "sha256": "2637312a057332f621428d1eef40b7b81c54b9b3b2c53790bffff94e34cf68a0",
          "sha1": "73cf4370df1e54bcddd35c9e8b68e808cc787338",
          "md5": "da3f2f4cda85e4774cb7fb624503ac09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-0.2.0-sources.jar",
          "url": "cyberfactions-api-0.2.0-sources.jar",
          "size": 28181,
          "sha512": "a1aace7c5f80d81c2ce6697e78fdef3f7afb135675c9ad9f2eb3b3b01f5fc5c2ba6f86277387a5e3829726a6a2d17169e934053c2e8375e9cc71595a307c6de7",
          "sha256": "01d8bdf5a7b434c78f3ae849f8391f7f3f72f8215f4f28e097b1b0bdc5a077ef",
          "sha1": "e84e6a00fc2410d4c4426c5957e65d69ded4c24b",
          "md5": "9852ea0deb26f61136dc10ef0c8cf0f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-0.2.0-javadoc.jar",
          "url": "cyberfactions-api-0.2.0-javadoc.jar",
          "size": 292127,
          "sha512": "554f4cddb90f10d5d7958faec7ec831b88298a420c1ba8f688a55ecfbb655827fc3422945e149c6c77e8bdc22a43cf62f497466e219f8ad12672579704d49ae9",
          "sha256": "8ae0405a181e1c0cdf970aa56ec132507fae893e4a81a26dd8bf7a27286f34ec",
          "sha1": "3e74d2bed1db2672b26604156c39de56248f1679",
          "md5": "bb00fbba3bc548023c8a050add3130f6"
        }
      ]
    }
  ]
}
