{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.billyrosty",
    "module": "cyberfactions-api",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4.jar",
          "url": "cyberfactions-api-1.0.4.jar",
          "size": 22238,
          "sha512": "87162654c36ce7b7c554ad749e662e5856c0564743b70b856f879a678a21aac2e16f0e0fcafdec7e4ed9af900fc0deb728d34cf1bb7ab6c3d4cf14784762d79a",
          "sha256": "7dc192697cf63362b6756a1898a9640e914d36516634d2db178fb9d789d65202",
          "sha1": "da0d497920e0b9d1df27a824589d477aaf376eb0",
          "md5": "7d95c95c04eae15ad072845758c63d47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4.jar",
          "url": "cyberfactions-api-1.0.4.jar",
          "size": 22238,
          "sha512": "87162654c36ce7b7c554ad749e662e5856c0564743b70b856f879a678a21aac2e16f0e0fcafdec7e4ed9af900fc0deb728d34cf1bb7ab6c3d4cf14784762d79a",
          "sha256": "7dc192697cf63362b6756a1898a9640e914d36516634d2db178fb9d789d65202",
          "sha1": "da0d497920e0b9d1df27a824589d477aaf376eb0",
          "md5": "7d95c95c04eae15ad072845758c63d47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4-sources.jar",
          "url": "cyberfactions-api-1.0.4-sources.jar",
          "size": 13557,
          "sha512": "dc029ff44758216552735998936e3bee8f0113000d2529c0a8698c14f3463b01cebb432c40030fbe7d86c189acd7fa4e6f72ad3305bfd4e8eb93ffd7c4070d75",
          "sha256": "e22319a7187c2b037ad8e8d66fce276f6f8176078d6c5596f856c14abe60ac4d",
          "sha1": "439fd49e4f245db9a84ce295b3425c95d4f461a2",
          "md5": "1813148203a9731dbc25b9d9d1d894f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4-javadoc.jar",
          "url": "cyberfactions-api-1.0.4-javadoc.jar",
          "size": 210534,
          "sha512": "34fc098c6790bb799b175f2ad3db6ee86cad91ab0ec6839888ef55204f3f42bf767d3d4243ad05138166fa99dedd2354a5f6a7c363e17fc1e455ae478261f995",
          "sha256": "46157d701e5f34cde467d4f7855b2981bbd0ed65a1858568a3673711b289c581",
          "sha1": "1376ba4b11f59441834a389940ad0a3d9cbd4427",
          "md5": "e394d4dcaf69f6904c564f2ef472928b"
        }
      ]
    }
  ]
}
