{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.billyrosty",
    "module": "cyberfactions-api",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4.jar",
          "url": "cyberfactions-api-1.0.4.jar",
          "size": 22238,
          "sha512": "c4314426b64b49c4c7b480e21977b2a7c67cba14cb9fe2faf6b4f7a4a4e46f7238f2b05e3117aa1c0c40cce9562336ee93ec63804f011a0b748c0ad13f629171",
          "sha256": "5242fb0b5c93fd422ee2b90226c97d05ba9eaa5ae9d7a6f876f118d544a81637",
          "sha1": "20dc99c76c694e4afb3f1ba6166df2f501999fd5",
          "md5": "8758721a86d1541286040a7d684e74e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4.jar",
          "url": "cyberfactions-api-1.0.4.jar",
          "size": 22238,
          "sha512": "c4314426b64b49c4c7b480e21977b2a7c67cba14cb9fe2faf6b4f7a4a4e46f7238f2b05e3117aa1c0c40cce9562336ee93ec63804f011a0b748c0ad13f629171",
          "sha256": "5242fb0b5c93fd422ee2b90226c97d05ba9eaa5ae9d7a6f876f118d544a81637",
          "sha1": "20dc99c76c694e4afb3f1ba6166df2f501999fd5",
          "md5": "8758721a86d1541286040a7d684e74e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4-sources.jar",
          "url": "cyberfactions-api-1.0.4-sources.jar",
          "size": 13557,
          "sha512": "499ad4cde2309e284f58d1dc172781d038d17e34112125d8fb55eda137984c6fdce34bb398668d14b578dd293ec2315d71db87109f2a4eca3cfff7bb156d4876",
          "sha256": "c111957369ef82d84f620a39227903649ff8286ec3f08a7f7c375fa28e529cfe",
          "sha1": "a5cfb9ac2ed86fb671f66de81cb1fcc8f81dac66",
          "md5": "84392cbcc0521f27a0c3724c7440213d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyberfactions-api-1.0.4-javadoc.jar",
          "url": "cyberfactions-api-1.0.4-javadoc.jar",
          "size": 210534,
          "sha512": "32fc48ee1f648cee31a599f003a70b272a308fb1ebb1d9fe8a52d9ef6faa7aa995009d81cbb5d4dbcae794db6b2fca8bed00f0813773208a57afd7d4a3e58ec8",
          "sha256": "67e80c6387cdb0f93fb0480dad7db430d509acab75e50504df1e0f035e4cd0e6",
          "sha1": "b39992c82d496a15219aef587ae333d032c4d19d",
          "md5": "ab2cb0bfa5486be6b63bc125eb266efd"
        }
      ]
    }
  ]
}
